/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { FileUploadService } from "../fileUpload.service";
import { FileUploadCreateInput } from "./FileUploadCreateInput";
import { FileUpload } from "./FileUpload";
import { FileUploadFindManyArgs } from "./FileUploadFindManyArgs";
import { FileUploadWhereUniqueInput } from "./FileUploadWhereUniqueInput";
import { FileUploadUpdateInput } from "./FileUploadUpdateInput";

export class FileUploadControllerBase {
  constructor(protected readonly service: FileUploadService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: FileUpload })
  async createFileUpload(
    @common.Body() data: FileUploadCreateInput
  ): Promise<FileUpload> {
    return await this.service.createFileUpload({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [FileUpload] })
  @ApiNestedQuery(FileUploadFindManyArgs)
  async fileUploads(@common.Req() request: Request): Promise<FileUpload[]> {
    const args = plainToClass(FileUploadFindManyArgs, request.query);
    return this.service.fileUploads({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: FileUpload })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async fileUpload(
    @common.Param() params: FileUploadWhereUniqueInput
  ): Promise<FileUpload | null> {
    const result = await this.service.fileUpload({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: FileUpload })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateFileUpload(
    @common.Param() params: FileUploadWhereUniqueInput,
    @common.Body() data: FileUploadUpdateInput
  ): Promise<FileUpload | null> {
    try {
      return await this.service.updateFileUpload({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: FileUpload })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteFileUpload(
    @common.Param() params: FileUploadWhereUniqueInput
  ): Promise<FileUpload | null> {
    try {
      return await this.service.deleteFileUpload({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
