/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AudioGuideFile } from "./AudioGuideFile";
import { AudioGuideFileCountArgs } from "./AudioGuideFileCountArgs";
import { AudioGuideFileFindManyArgs } from "./AudioGuideFileFindManyArgs";
import { AudioGuideFileFindUniqueArgs } from "./AudioGuideFileFindUniqueArgs";
import { DeleteAudioGuideFileArgs } from "./DeleteAudioGuideFileArgs";
import { AudioGuideFileService } from "../audioGuideFile.service";
@graphql.Resolver(() => AudioGuideFile)
export class AudioGuideFileResolverBase {
  constructor(protected readonly service: AudioGuideFileService) {}

  async _audioGuideFilesMeta(
    @graphql.Args() args: AudioGuideFileCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [AudioGuideFile])
  async audioGuideFiles(
    @graphql.Args() args: AudioGuideFileFindManyArgs
  ): Promise<AudioGuideFile[]> {
    return this.service.audioGuideFiles(args);
  }

  @graphql.Query(() => AudioGuideFile, { nullable: true })
  async audioGuideFile(
    @graphql.Args() args: AudioGuideFileFindUniqueArgs
  ): Promise<AudioGuideFile | null> {
    const result = await this.service.audioGuideFile(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => AudioGuideFile)
  async deleteAudioGuideFile(
    @graphql.Args() args: DeleteAudioGuideFileArgs
  ): Promise<AudioGuideFile | null> {
    try {
      return await this.service.deleteAudioGuideFile(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
