/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Attraction } from "./Attraction";
import { AttractionCountArgs } from "./AttractionCountArgs";
import { AttractionFindManyArgs } from "./AttractionFindManyArgs";
import { AttractionFindUniqueArgs } from "./AttractionFindUniqueArgs";
import { DeleteAttractionArgs } from "./DeleteAttractionArgs";
import { AttractionService } from "../attraction.service";
@graphql.Resolver(() => Attraction)
export class AttractionResolverBase {
  constructor(protected readonly service: AttractionService) {}

  async _attractionsMeta(
    @graphql.Args() args: AttractionCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Attraction])
  async attractions(
    @graphql.Args() args: AttractionFindManyArgs
  ): Promise<Attraction[]> {
    return this.service.attractions(args);
  }

  @graphql.Query(() => Attraction, { nullable: true })
  async attraction(
    @graphql.Args() args: AttractionFindUniqueArgs
  ): Promise<Attraction | null> {
    const result = await this.service.attraction(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Attraction)
  async deleteAttraction(
    @graphql.Args() args: DeleteAttractionArgs
  ): Promise<Attraction | null> {
    try {
      return await this.service.deleteAttraction(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
